FROM registry.access.redhat.com/ubi10/python-314-minimal@sha256:92f2b9ef3d2fe255f5a2200f97bf4f14a95dc120bd19bcbc9f84a2f10e4af683 AS base
COPY --from=ghcr.io/astral-sh/uv:0.11.28@sha256:0f36cb9361a3346885ca3677e3767016687b5a170c1a6b88465ec14aefec90aa /uv /bin/uv

COPY LICENSE /licenses/

ENV \
    # unbuffered output for easier logging
    PYTHONUNBUFFERED=1 \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=$APP_ROOT \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true

USER root
RUN microdnf install -y make  && microdnf clean all && rm -rf /var/cache/yum
USER 1001

COPY packages/automated_actions_client/README.md ./
COPY packages/automated_actions_client/pyproject.toml ./
RUN uv sync --no-install-project

COPY packages/automated_actions_client/Makefile ./
COPY packages/automated_actions_client/tests ./tests
COPY packages/automated_actions_client/automated_actions_client ./automated_actions_client
RUN uv sync

#
# Test image
#
FROM base AS test
USER root
# allow user to create cache dirs and files, e.g. .ruff_cache, .coverage, ...
RUN chown -R 1001:0 ./
USER 1001

RUN make test

#
# PyPI publish image
#
FROM test AS pypi
# Secrets are owned by root and are not readable by others :(
USER root
RUN --mount=type=secret,id=app-sre-pypi-credentials/token UV_PUBLISH_TOKEN=$(cat /run/secrets/app-sre-pypi-credentials/token) make pypi
USER 1001
