FROM registry.access.redhat.com/ubi10/python-314-minimal@sha256:1184f0930506ef3c5d2b6c34d3dee04f5cd82f6960db5ea182f7559763da144d AS base
COPY --from=ghcr.io/astral-sh/uv:0.12.12@sha256:73d2665b478d8fa2de1cf105c6841f8e9cb6b09e568fc7700440c09f8fcd7ac4 /uv /bin/uv

COPY LICENSE /licenses/

ENV \
    # unbuffered output for easier logging
    PYTHONUNBUFFERED=1 \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=$APP_ROOT \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true

USER root
RUN microdnf install -y make  && microdnf clean all && rm -rf /var/cache/yum
USER 1001

COPY packages/automated_actions_client/README.md ./
COPY packages/automated_actions_client/pyproject.toml ./
RUN uv sync --no-install-project

COPY packages/automated_actions_client/Makefile ./
COPY packages/automated_actions_client/tests ./tests
COPY packages/automated_actions_client/automated_actions_client ./automated_actions_client
RUN uv sync

#
# Test image
#
FROM base AS test
USER root
# allow user to create cache dirs and files, e.g. .ruff_cache, .coverage, ...
RUN chown -R 1001:0 ./
USER 1001

RUN make test

#
# PyPI publish image
#
FROM test AS pypi
# Secrets are owned by root and are not readable by others :(
USER root
RUN --mount=type=secret,id=app-sre-pypi-credentials/token UV_PUBLISH_TOKEN=$(cat /run/secrets/app-sre-pypi-credentials/token) make pypi
USER 1001
