#
# Base image with defaults for all stages
FROM registry.access.redhat.com/ubi9/python-314-minimal@sha256:3132aa18ce0d6843d256f8f646d660b6c5bc1ac9f60957d752204012bd3a5b4a AS base

COPY LICENSE /licenses/

ENV APP_ROOT=/opt/app-root
ENV \
    # unbuffered output for easier logging
    PYTHONUNBUFFERED=1 \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=${APP_ROOT} \
    # compile bytecode for faster startup
    UV_COMPILE_BYTECODE="true" \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true \
    BASH_ENV="${APP_ROOT}/bin/activate" \
    ENV="${APP_ROOT}/bin/activate" \
    PROMPT_COMMAND=". ${APP_ROOT}/bin/activate" \
    IS_TESTED_FLAG="/tmp/is_tested"

WORKDIR ${APP_ROOT}/src

USER 0
# Install base dependencies
RUN microdnf install -y make && microdnf clean all
USER 1001

#
# Builder image
#
FROM registry.access.redhat.com/ubi9/python-314@sha256:ce3cf9647cc776fb6fd1171431d92a0ab15123b93494909df8ba4a46099e6562 AS builder
COPY --from=ghcr.io/astral-sh/uv:0.12.0@sha256:606e70c71c852d03f611b1e56a195d08648507018a7057fab82c4974c4eae105 /uv /bin/uv

ENV \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=${APP_ROOT} \
    # compile bytecode for faster startup
    UV_COMPILE_BYTECODE="true" \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true

# I don't want to mess with permission issues in the builder image. We use a non-root user in the final images
USER 0

# Install build dependencies
RUN dnf install -y gcc krb5-devel && dnf clean all && rm -rf /var/cache/yum

COPY pyproject.toml uv.lock ./
# automated_actions_client is a dependency of automated_actions_cli
COPY packages/automated_actions ./packages/automated_actions
COPY packages/automated_actions_client ./packages/automated_actions_client
COPY packages/automated_actions_cli ./packages/automated_actions_cli
COPY packages/automated_actions_utils ./packages/automated_actions_utils

COPY packages/integration_tests/ ./packages/integration_tests/
RUN cd ./packages/integration_tests/ && uv sync


#
# Test image
#
FROM base AS test
COPY --from=ghcr.io/astral-sh/uv:0.12.0@sha256:606e70c71c852d03f611b1e56a195d08648507018a7057fab82c4974c4eae105 /uv /bin/uv

COPY --from=builder --chown=1001:0 ${APP_ROOT} ${APP_ROOT}
COPY packages/integration_tests/Makefile ./packages/integration_tests/

RUN make -C packages/integration_tests test
RUN touch ${IS_TESTED_FLAG}

#
# Production image
#
FROM base AS prod
COPY --from=builder ${APP_ROOT} ${APP_ROOT}
COPY --from=test ${IS_TESTED_FLAG} ${IS_TESTED_FLAG}

WORKDIR ${APP_ROOT}/src/packages/integration_tests

ENTRYPOINT ["pytest", "-p", "no:cacheprovider"]
CMD ["tests"]
