FROM registry.access.redhat.com/ubi9/python-312@sha256:a3af61fdae215cd8d8f67f8f737064b353dc0592567099de48b3c2563314810d AS base
COPY --from=ghcr.io/astral-sh/uv:0.8.15@sha256:a5727064a0de127bdb7c9d3c1383f3a9ac307d9f2d8a391edc7896c54289ced0 /uv /bin/uv

COPY LICENSE /licenses/

ENV \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=$APP_ROOT \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true


COPY packages/automated_actions_client/README.md ./
COPY packages/automated_actions_client/pyproject.toml ./
RUN uv sync --no-install-project

COPY packages/automated_actions_client/openapi_python_client_templates ./openapi_python_client_templates
COPY packages/automated_actions_client/Makefile ./
COPY packages/automated_actions_client/tests ./tests
COPY packages/automated_actions_client/automated_actions_client ./automated_actions_client
RUN uv sync

#
# Test image
#
FROM base AS test
USER root
# allow user to create cache dirs and files, e.g. .ruff_cache, .coverage, ...
RUN chown -R 1001:0 ./
USER 1001

RUN make test

#
# PyPI publish image
#
FROM test AS pypi
# Secrets are owned by root and are not readable by others :(
USER root
RUN --mount=type=secret,id=app-sre-pypi-credentials/token UV_PUBLISH_TOKEN=$(cat /run/secrets/app-sre-pypi-credentials/token) make pypi
USER 1001
