{
 "title": "Automated Actions Production Logs",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expression": "fields @timestamp, message | filter kubernetes.container_name == \"web\" | sort @timestamp asc",
     "logGroups": [
      {
       "accountId": "744086762512",
       "arn": "arn:aws:logs:us-east-1:744086762512:log-group:appsrep09ue1.automated-actions-production:*",
       "name": "appsrep09ue1.automated-actions-production"
      }
     ],
     "metricEditorMode": 1,
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Worker Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expression": "fields @timestamp, message | filter kubernetes.container_name == \"worker\" | sort @timestamp asc",
       "logGroups": [
        {
         "accountId": "744086762512",
         "arn": "arn:aws:logs:us-east-1:744086762512:log-group:appsrep09ue1.automated-actions-production:*",
         "name": "appsrep09ue1.automated-actions-production"
        }
       ],
       "metricEditorMode": 1,
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "OPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "OPA Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expression": "fields @timestamp, message | filter kubernetes.container_name == \"opa\" | sort @timestamp asc",
       "logGroups": [
        {
         "accountId": "744086762512",
         "arn": "arn:aws:logs:us-east-1:744086762512:log-group:appsrep09ue1.automated-actions-production:*",
         "name": "appsrep09ue1.automated-actions-production"
        }
       ],
       "metricEditorMode": 1,
       "queryMode": "Logs",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}