{
 "title": "Automated Actions Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "production : appsrep09ue1-prometheus, stage : appsres09ue1-prometheus, integration : appsres09ue1-prometheus"
   },
   {
    "name": "aws_env",
    "query": "production : appsrep11ue1-prometheus, stage : appsres11ue1-prometheus, integration : appsres11ue1-prometheus"
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "aws_datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_request_duration_seconds_count,namespace)"
    }
   },
   {
    "name": "prober_name",
    "query": {
     "query": "label_values(script_success,script)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Router", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (exported_namespace)(rate(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\", code=\"5xx\"}[5m])) /\nsum by (exported_namespace)(rate(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(rate(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\",code=\"5xx\"}[$__range])) or vector(0) / sum(rate(haproxy_backend_http_responses_total{exported_namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "API request rate per method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_request_duration_seconds_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API request latency per method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (method, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\"}[5m])))",
     "legendFormat": "{{method}}-p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (method, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\"}[5m])))",
     "legendFormat": "{{method}}-p99"
    }
   ]
  },
  {
   "title": "script_exporter prober",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "targets": [
    {
     "expr": "min by (script) (script_success{script=\"$prober_name\"})",
     "legendFormat": "{{script}}"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Queue actions requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (name) (rate(automated_actions_action_elapsed_seconds_count{namespace=\"$namespace\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue actions latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (name, le) (rate(automated_actions_action_elapsed_seconds_bucket{namespace=\"$namespace\"}[60m])))",
     "legendFormat": "{{name}}-p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (name, le) (rate(automated_actions_action_elapsed_seconds_bucket{namespace=\"$namespace\"}[60m])))",
     "legendFormat": "{{name}}-p99"
    }
   ]
  },
  {
   "title": "SQS messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "aws_sqs_approximate_number_of_messages_visible_average{queue_name=\"automated-actions-celery-${env:text}\"}",
     "legendFormat": "visible messages"
    }
   ]
  },
  { "title": "DynamoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "User table read usage (average units/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_read_capacity_units_average{table_name=~\"aa-${env:text}-user\"}",
     "legendFormat": "consumed-{{table_name}}"
    },
    {
     "expr": "aws_dynamodb_provisioned_read_capacity_units_average{table_name=~\"aa-${env:text}-user\"}",
     "legendFormat": "provisioned-{{table_name}}"
    }
   ]
  },
  {
   "title": "User table write usage (average units/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_write_capacity_units_average{table_name=~\"aa-${env:text}-user\"}",
     "legendFormat": "consumed-{{table_name}}"
    },
    {
     "expr": "aws_dynamodb_provisioned_write_capacity_units_average{table_name=~\"aa-${env:text}-user\"}",
     "legendFormat": "provisioned-{{table_name}}"
    }
   ]
  },
  {
   "title": "User table throttled requests (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "aws_dynamodb_throttled_requests_sample_count{table_name=~\"aa-${env:text}-user\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Actions table read usage (average units/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_read_capacity_units_average{table_name=~\"aa-${env:text}-actions\"}",
     "legendFormat": "consumed-{{table_name}}"
    },
    {
     "expr": "aws_dynamodb_provisioned_read_capacity_units_average{table_name=~\"aa-${env:text}-actions\"}",
     "legendFormat": "provisioned-{{table_name}}"
    }
   ]
  },
  {
   "title": "Actions table write usage (average units/second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "aws_dynamodb_consumed_write_capacity_units_average{table_name=~\"aa-${env:text}-actions\"}",
     "legendFormat": "consumed-{{table_name}}"
    },
    {
     "expr": "aws_dynamodb_provisioned_write_capacity_units_average{table_name=~\"aa-${env:text}-actions\"}",
     "legendFormat": "provisioned-{{table_name}}"
    }
   ]
  },
  {
   "title": "Actions table throttled requests (count)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "aws_dynamodb_throttled_requests_sample_count{table_name=~\"aa-${env:text}-actions\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Pod stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", container=\"web\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"web\", resource=\"memory\"})",
       "legendFormat": "Memory Limit"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"web\", resource=\"memory\"})",
       "legendFormat": "Memory Request"
      }
     ]
    },
    {
     "title": "API Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\", pod=~\"^automated-actions-[^-]+-[^-]+$\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"^automated-actions-[^-]+-[^-]+$\", resource=\"cpu\"})",
       "legendFormat": "CPU Requests"
      }
     ]
    },
    {
     "title": "Worker Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", container=\"worker\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"worker\", resource=\"memory\"})",
       "legendFormat": "Memory Limit"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"worker\", resource=\"memory\"})",
       "legendFormat": "Memory Request"
      }
     ]
    },
    {
     "title": "Worker Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\", pod=~\"^automated-actions-worker-[^-]+-[^-]+$\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"^automated-actions-worker-[^-]+-[^-]+$\", resource=\"cpu\"})",
       "legendFormat": "CPU Requests"
      }
     ]
    },
    {
     "title": "OPA Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", container=\"opa\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"opa\", resource=\"memory\"})",
       "legendFormat": "Memory Limit"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"opa\", resource=\"memory\"})",
       "legendFormat": "Memory Request"
      }
     ]
    },
    {
     "title": "OPA Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\", pod=~\"^opa-[^-]+-[^-]+$\"}",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"^opa-[^-]+-[^-]+$\", resource=\"cpu\"})",
       "legendFormat": "CPU Requests"
      }
     ]
    }
   ]
  }
 ]
}