---
apiVersion: v1
kind: Template
metadata:
  name: periodic-no-op
objects:
- kind: CronJob
  apiVersion: batch/v1
  metadata:
    name: periodic-no-op
    labels:
      app.kubernetes.io/name: periodic-no-op
  spec:
    schedule: ${SCHEDULE}
    concurrencyPolicy: Forbid
    jobTemplate:
      metadata:
        labels:
          app.kubernetes.io/cronjob: periodic-no-op
      spec:
        backoffLimit: ${{BACKOFF_LIMIT}}
        activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}
        template:
          metadata:
            labels:
              app.kubernetes.io/cronjob: periodic-no-op
          spec:
            restartPolicy: OnFailure
            containers:
            - name: automated-action-cli
              image: "${IMAGE}:${IMAGE_TAG}"
              imagePullPolicy: ${IMAGE_PULL_POLICY}
              command: ["/usr/bin/uv", "run", "automated-actions", "no-op"]
              env:
              - name: AA_URL
                value: ${AA_URL}
              - name: AA_TOKEN
                value: ${AA_TOKEN}
parameters:
- name: IMAGE
  value: quay.io/redhat-services-prod/app-sre-tenant/automated-actions-main/automated-actions-cli-main
- name: IMAGE_TAG
  value: "latest"
- name: IMAGE_PULL_POLICY
  value: "Always"
- name: SCHEDULE
  value: "* * * * *"
- name: BACKOFF_LIMIT
  value: "2"
- name: ACTIVE_DEADLINE_SECONDS
  value: "60"
- name: AA_URL
  description: URL of the API
  required: true
- name: AA_TOKEN
  description: Access token for the automated-actions instance
  required: true
